/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carsalesclient.form;

import java.awt.event.ActionListener;
import javax.swing.JCheckBoxMenuItem;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author user
 */
public class MainForm extends javax.swing.JFrame {
    
    public MainForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMain = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        menuItemCreateNewInvoice = new javax.swing.JMenuItem();
        menuItemSeeAllInvoices = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemAddSalesman = new javax.swing.JMenuItem();
        menuItemSeeAllSalesmen = new javax.swing.JMenuItem();
        menuAddNewCar = new javax.swing.JMenu();
        menuItemAddNewCar = new javax.swing.JMenuItem();
        menuItemSeeAllCars = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemAddNewCustomer = new javax.swing.JMenuItem();
        menuItemSeeAllCustomers = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menuItemEnglish = new javax.swing.JCheckBoxMenuItem();
        menuItemSerbian = new javax.swing.JCheckBoxMenuItem();
        menuItemLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Sales Tracker");

        lblMain.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        lblMain.setText("jLabel1");

        jMenu5.setText("Invoice");
        jMenu5.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N

        menuItemCreateNewInvoice.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        menuItemCreateNewInvoice.setText("Create new invoice");
        menuItemCreateNewInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreateNewInvoiceActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemCreateNewInvoice);

        menuItemSeeAllInvoices.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        menuItemSeeAllInvoices.setText("See all invoices");
        jMenu5.add(menuItemSeeAllInvoices);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Salesmen");
        jMenu2.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N

        menuItemAddSalesman.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        menuItemAddSalesman.setText("Add new salesman");
        jMenu2.add(menuItemAddSalesman);

        menuItemSeeAllSalesmen.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        menuItemSeeAllSalesmen.setText("See all salesmen");
        menuItemSeeAllSalesmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeeAllSalesmenActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemSeeAllSalesmen);

        jMenuBar1.add(jMenu2);

        menuAddNewCar.setText("Cars");
        menuAddNewCar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N

        menuItemAddNewCar.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        menuItemAddNewCar.setText("Add new car");
        menuItemAddNewCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddNewCarActionPerformed(evt);
            }
        });
        menuAddNewCar.add(menuItemAddNewCar);

        menuItemSeeAllCars.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        menuItemSeeAllCars.setText("See all cars");
        menuItemSeeAllCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeeAllCarsActionPerformed(evt);
            }
        });
        menuAddNewCar.add(menuItemSeeAllCars);

        jMenuBar1.add(menuAddNewCar);

        jMenu1.setText("Customers");
        jMenu1.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N

        menuItemAddNewCustomer.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        menuItemAddNewCustomer.setText("Add new customer");
        menuItemAddNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddNewCustomerActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemAddNewCustomer);

        menuItemSeeAllCustomers.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        menuItemSeeAllCustomers.setText("See all customers");
        menuItemSeeAllCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeeAllCustomersActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSeeAllCustomers);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Options");
        jMenu3.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N

        jMenu4.setText("Language");
        jMenu4.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N

        menuItemEnglish.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        menuItemEnglish.setSelected(true);
        menuItemEnglish.setText("English");
        jMenu4.add(menuItemEnglish);

        menuItemSerbian.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        menuItemSerbian.setText("Serbian");
        jMenu4.add(menuItemSerbian);

        jMenu3.add(jMenu4);

        menuItemLogOut.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        menuItemLogOut.setText("Log out");
        jMenu3.add(menuItemLogOut);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMain, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMain)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSeeAllCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeeAllCarsActionPerformed
    }//GEN-LAST:event_menuItemSeeAllCarsActionPerformed

    private void menuItemSeeAllSalesmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeeAllSalesmenActionPerformed
    }//GEN-LAST:event_menuItemSeeAllSalesmenActionPerformed

    private void menuItemAddNewCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddNewCarActionPerformed
    }//GEN-LAST:event_menuItemAddNewCarActionPerformed

    private void menuItemAddNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddNewCustomerActionPerformed
    }//GEN-LAST:event_menuItemAddNewCustomerActionPerformed

    private void menuItemSeeAllCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeeAllCustomersActionPerformed
    }//GEN-LAST:event_menuItemSeeAllCustomersActionPerformed

    private void menuItemCreateNewInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreateNewInvoiceActionPerformed
    }//GEN-LAST:event_menuItemCreateNewInvoiceActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblMain;
    private javax.swing.JMenu menuAddNewCar;
    private javax.swing.JMenuItem menuItemAddNewCar;
    private javax.swing.JMenuItem menuItemAddNewCustomer;
    private javax.swing.JMenuItem menuItemAddSalesman;
    private javax.swing.JMenuItem menuItemCreateNewInvoice;
    private javax.swing.JCheckBoxMenuItem menuItemEnglish;
    private javax.swing.JMenuItem menuItemLogOut;
    private javax.swing.JMenuItem menuItemSeeAllCars;
    private javax.swing.JMenuItem menuItemSeeAllCustomers;
    private javax.swing.JMenuItem menuItemSeeAllInvoices;
    private javax.swing.JMenuItem menuItemSeeAllSalesmen;
    private javax.swing.JCheckBoxMenuItem menuItemSerbian;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getMenuItemEnglish() {
        return menuItemEnglish;
    }
    
    public JMenuItem getMenuItemSerbian() {
        return menuItemSerbian;
    }
    
    public void miCreateNewInvoiceAddActionListener(ActionListener actionListener){
        menuItemCreateNewInvoice.addActionListener(actionListener);
    }
    
    public void miSeeAllInvoicesAddActionListener(ActionListener actionListener){
        menuItemSeeAllInvoices.addActionListener(actionListener);
    }
    
    public void miAddNewSalesmanAddActionListener(ActionListener actionListener){
        menuItemAddSalesman.addActionListener(actionListener);
    }
    
    public void miSeeAllSalesmenAddActionListener(ActionListener actionListener){
        menuItemSeeAllSalesmen.addActionListener(actionListener);
    }
    
    public void miAddNewCarAddActionListener(ActionListener actionListener){
        menuItemAddNewCar.addActionListener(actionListener);
    }
    
    public void miSeeAllCarsAddActionListener(ActionListener actionListener){
        menuItemSeeAllCars.addActionListener(actionListener);
    }
    
    public void miAddNewCustomerAddActionListener(ActionListener actionListener){
        menuItemAddNewCustomer.addActionListener(actionListener);
    }
    
    public void miSeeAllCustomersAddActionListener(ActionListener actionListener){
        menuItemSeeAllCustomers.addActionListener(actionListener);
    }
    
    public JLabel getLblMain() {
        return lblMain;
    }

    public JMenuItem getMenuItemCreateNewInvoice() {
        return menuItemCreateNewInvoice;
    }
    
    public void miEnglishAddActionListener(ActionListener actionListener){
        menuItemEnglish.addActionListener(actionListener);
    }
    
    public void miSerbianAddActionListener(ActionListener actionListener){
        menuItemSerbian.addActionListener(actionListener);
    }
}
